import fs from 'node:fs/promises'
import path from 'node:path'

interface RouteConfig {
    path: string
    title?: string
    description?: string
}

const ROUTES: RouteConfig[] = [
    {
        path: '/',
        title: 'Minecraft Item List - Instant Search, Block Stats & Loot Database',
    },
    {
        path: '/impressum',
        title: 'Impressum & Privacy Policy - Minecraft Item List',
        description:
            'Legal notice and privacy policy for Minecraft Item List.',
    },
    {
        path: '/bulk',
        title: 'Custom List Builder & Database Filter - Minecraft Item List',
        description:
            'Filter, query, and export custom Minecraft item datasets with all block properties, loot tables, and mechanics.',
    },
    {
        path: '/list',
        title: 'Item Catalog & Directory - Minecraft Item List',
        description:
            'Browse the full categorized list of Minecraft items and blocks.',
    },
]

async function prerender() {
    const rootDir = process.cwd()
    const distDir = path.join(rootDir, 'dist')
    const templatePath = path.join(distDir, 'index.html')
    const serverEntryPath = path.join(distDir, 'server', 'entry-server.js')

    console.log('🚀 Starting pre-rendering...')

    // Read template HTML generated by client build
    const template = await fs.readFile(templatePath, 'utf-8')

    // Import the compiled SSR render function
    const { render } = await import(serverEntryPath)

    for (const route of ROUTES) {
        console.log(`  📄 Pre-rendering route: ${route.path}`)
        const appHtml = render(route.path)

        let html = template
        if (html.includes('<!--ssr-outlet-->')) {
            html = html.replace('<!--ssr-outlet-->', appHtml)
        } else {
            html = html.replace(
                /<div id="root">[\s\S]*?<\/div>/,
                `<div id="root">${appHtml}</div>`
            )
        }

        // Custom titles and descriptions per route
        if (route.title) {
            html = html.replace(
                /<title>[\s\S]*?<\/title>/,
                `<title>\n            ${route.title}\n        </title>`
            )
            html = html.replace(
                /<meta\s+property="og:title"\s+content="[^"]*"/,
                `<meta property="og:title" content="${route.title}"`
            )
            html = html.replace(
                /<meta\s+name="twitter:title"\s+content="[^"]*"/,
                `<meta name="twitter:title" content="${route.title}"`
            )
        }

        if (route.description) {
            html = html.replace(
                /<meta\s+name="description"\s+content="[^"]*"/,
                `<meta\n            name="description"\n            content="${route.description}"\n        />`
            )
            html = html.replace(
                /<meta\s+property="og:description"\s+content="[^"]*"/,
                `<meta\n            property="og:description"\n            content="${route.description}"\n        />`
            )
            html = html.replace(
                /<meta\s+name="twitter:description"\s+content="[^"]*"/,
                `<meta\n            name="twitter:description"\n            content="${route.description}"\n        />`
            )
        }

        // Canonical URL per route
        if (route.path !== '/') {
            const canonicalUrl = `https://l3-n0x.github.io/minecraft-item-list${route.path}`
            html = html.replace(
                /<link\s+rel="canonical"\s+href="[^"]*"/,
                `<link\n            rel="canonical"\n            href="${canonicalUrl}"\n        />`
            )
            html = html.replace(
                /<meta\s+property="og:url"\s+content="[^"]*"/,
                `<meta\n            property="og:url"\n            content="${canonicalUrl}"\n        />`
            )
        }

        if (route.path === '/') {
            await fs.writeFile(templatePath, html, 'utf-8')
            // Also write 404.html for GitHub Pages fallback
            const fallbackPath = path.join(distDir, '404.html')
            await fs.writeFile(fallbackPath, html, 'utf-8')
        } else {
            const routeDir = path.join(distDir, route.path.slice(1))
            await fs.mkdir(routeDir, { recursive: true })
            await fs.writeFile(path.join(routeDir, 'index.html'), html, 'utf-8')
        }
    }

    // Clean up dist/server
    const serverDir = path.join(distDir, 'server')
    try {
        await fs.rm(serverDir, { recursive: true, force: true })
    } catch {
        // Ignore error
    }

    console.log('✅ Pre-rendering complete! Static HTML generated.')
}

prerender().catch((err) => {
    console.error('❌ Pre-rendering failed:', err)
    process.exit(1)
})
